name: JSON

on:
    push:
        branches: [main]
        paths:
            - "list/*"
            - "scripts/*"
            - ".github/workflows/json.yml"

    schedule:
        - cron: "0 0 * * *"

    workflow_dispatch:

jobs:
    psl:
        name: PSL
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - run: mkdir -p list

            - name: Download public_suffix_list.dat
              run: curl -o list/public_suffix_list.dat https://publicsuffix.org/list/public_suffix_list.dat

            - name: Convert public_suffix_list.dat to JSON
              run: node scripts/json.js

            - name: Commit
              env:
                  MINIFY_PERCENT: ${{ env.minify_percent }}
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "actions@github.com"
                  git add list/public_suffix_list.json
                  git commit --allow-empty -m "chore: convert PSL to JSON"
                  git push

            - name: Trigger Coolify Webhook
              run: |
                  curl -X POST "${{ secrets.WEBHOOK_URL }}" -H "Authorization: Bearer ${{ secrets.COOLIFY_API_KEY }}"
